const actionType = {
    SET_SCENICSPOT_DATA : "SET_SCENICSPOT_DATA",
    SET_CITYSCENICSPOT_DATA : "SET_CITYSCENICSPOT_DATA",
    BEGIN_DATA_REQUEST : "BEGIN_DATA_REQUEST",
    SUCCESS_DATA_REQUEST : "SUCCESS_DATA_REQUEST",
    FAIL_DATA_REQUEST : "FAIL_DATA_REQUEST"
}

export default actionType;